package net.teohdouglas.tidal.exceptions;

public class DropletInitException extends Exception {

	public DropletInitException() {
		super();
		// TODO Auto-generated constructor stub
	}

	public DropletInitException(final String message, final Throwable cause) {
		super(message, cause);
		// TODO Auto-generated constructor stub
	}

	public DropletInitException(final String message) {
		super(message);
		// TODO Auto-generated constructor stub
	}

	public DropletInitException(final Throwable cause) {
		super(cause);
		// TODO Auto-generated constructor stub
	}

	/**
	 * Auto-generated by Eclipse
	 */
	private static final long serialVersionUID = 9103596782124237189L;

}
