/*
 * Tidal, a communications aggregation and notification tool. 
 * Copyright (C) 2010 Douglas Teoh 
 * 
 * This program is free software: you can redistribute it and/or
 * modify it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or (at your
 * option) any later version. 
 * 
 * This program is distributed in the hope that it will be useful, but WITHOUT 
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more 
 * details. You should have received a copy of the GNU General Public License 
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */

package org.tidal_app.tidal.views;

import java.util.Collections;
import java.util.Iterator;

import org.tidal_app.tidal.views.models.DropletModel;

/**
 * Special type of droplet view, used for aggregating every other droplet to
 * form a pool.
 * 
 * @author douglas
 */
public final class PoolDropletView extends DropletView {

    /**
     * Auto generated by Eclipse
     */
    private static final long serialVersionUID = 2969852870930615462L;

    private static final DropletModel emptyModel = new DropletModel("Pool");

    public PoolDropletView() {
        super(emptyModel);
    }

    public void addRippleViews(final Iterator<RippleView> rippleViews) {
        while (rippleViews.hasNext()) {
            this.rippleViews.add(rippleViews.next());
        }
        Collections.sort(this.rippleViews);
    }

}
