package net.teohdouglas.tidal.views;

import java.awt.Color;
import java.awt.Font;
import java.util.Iterator;
import java.util.LinkedList;
import java.util.List;

import javax.swing.JLabel;
import javax.swing.JPanel;

import net.miginfocom.swing.MigLayout;
import net.teohdouglas.tidal.views.models.DropletContentModel;
import net.teohdouglas.tidal.views.models.DropletModel;

public class DropletView extends JPanel {

    /**
     * Auto generated by Eclipse
     */
    private static final long serialVersionUID = 4663093783495843321L;
    private final DropletModel dropletModel;
    private final List<RippleView> rippleViews;

    public DropletView(final DropletModel dropletModel) {
        super();
        this.dropletModel = dropletModel;
        rippleViews = new LinkedList<RippleView>();
        initView();
    }

    private void initView() {
        setLayout(new MigLayout());
        setBackground(Color.WHITE);

        JLabel dropletNameLabel = new JLabel(dropletModel.getDropletName());
        dropletNameLabel.setFont(new Font(Font.SANS_SERIF, Font.PLAIN, 13));
        add(dropletNameLabel);

        Iterator<DropletContentModel> contentModels =
            dropletModel.getDropletContents();

        while (contentModels.hasNext()) {
            rippleViews.add(new RippleView(contentModels.next()));
        }
    }

    public Iterator<RippleView> getRippleViews() {
        return rippleViews.iterator();
    }

}
