package net.teohdouglas.tidal.views;

import java.util.Collections;
import java.util.Iterator;

import net.teohdouglas.tidal.views.models.DropletModel;

/**
 * Special type of droplet view, used for aggregating every other droplet to
 * form a pool.
 * 
 * @author douglas
 */
public final class PoolDropletView extends DropletView {

    /**
     * Auto generated by Eclipse
     */
    private static final long serialVersionUID = 2969852870930615462L;

    private static final DropletModel emptyModel = new DropletModel("Pool");

    public PoolDropletView() {
        super(emptyModel);
    }

    public void addRippleViews(final Iterator<RippleView> rippleViews) {
        while (rippleViews.hasNext()) {
            this.rippleViews.add(rippleViews.next());
        }
        Collections.sort(this.rippleViews);
    }

}
